package org.imaginea.demo.model;


import java.util.Arrays;
import java.util.List;

/**
 * @author Charanjit Singh
 * <p>
 * cities
 */

public class Cities {

    public static List<String> cities = Arrays.asList(
            "Chakragaon S.O",
            "Chatham S.O",
            "Delanipur S.O",
            "Marine Jetty S.O",
            "Kalakada Doddipalle B.O",
            "Kotagudibanda B.O",
            "Thuvvapalle B.O",
            "Guttapalem B.O",
            "Vathalur B.O",
            "Adivikodiyambedu B.O",
            "Beerakuppam B.O",
            "Bytikodiyambedu B.O",
            "Govardhanagiri B.O",
            "Kannavaram B.O",
            "Mangadu Kothur B.O",
            "Pudupet B.O",
            "Tadukupet B.O",
            "Venkatapathi Rajuvaripet B.O",
            "Veerakaveri Rajapuram B.O",
            "Kothur Venkatapuram B.O",
            "Kakavedu B.O",
            "Aranyam Kandriga B.O",
            "Kemparapalem B.O",
            "Pasalavandlapalle B.O",
            "Yellutla B.O",
            "Ayyavaripalle B.O",
            "Gandaboyanapalle B.O",
            "Manchuru B.O",
            "Mugalamarrikothapalle B.O",
            "Nagarimadugu B.O",
            "Pullleticheruvupalle B.O",
            "Sakamvaripalle B.O",
            "Kadirirayacheruvu B.O",
            "Kalicherla B.O",
            "Kotakonda B.O",
            "Kukkarajupalle B.O",
            "Papepalle B.O",
            "Peddamandyam B.O",
            "Sangasamudram B.O",
            "Sarimadugu B.O",
            "Galivaripalle B.O",
            "Kona B.O",
            "Devalapalle B.O",
            "Chintalavaripalem B.O",
            "Gajulamandyam B.O",
            "Karakambadi B.O",
            "Kothapalem B.O",
            "Kummarapalle B.O",
            "Madhavamala B.O",
            "Mamanduru B.O",
            "Pillapalem B.O",
            "Thukivakam B.O",
            "Vedullacheruvu B.O",
            "D.N.Choultry B.O",
            "R.T.C.Bus Stand B.O",
            "Akkarampalli B.O",
            "Avilalal B.O",
            "A.P.H.B.Colony B.O",
            "Chiguruvada B.O",
            "Satyanarayanapuram B.O",
            "Srinivasanagar B.O",
            "Chellur B.O",
            "Gudimallam B.O",
            "Madibaka B.O",
            "Munagalapalem B.O",
            "Ravillavarikandriga B.O",
            "Athur B.O",
            "Cotton Mills B.O",
            "T.T.D.Press B.O",
            "Mangalam B.O",
            "Applayagunta B.O",
            "Brahmanapattu B.O",
            "Obularajukandriga B.O",
            "Panapakam B.O",
            "Peddagorpadu B.O",
            "Peddaramapuram B.O",
            "Pakala Kothakota B.O",
            "Pothukanuma B.O",
            "Sankampalle B.O",
            "Venuthanapalle B.O",
            "Bodevandlapalle B.O",
            "Chinthagunta B.O",
            "Chitticherla B.O",
            "Dudhevaripalle B.O",
            "Kotabailu B.O",
            "Kotakadapalle B.O",
            "Nerabailu B.O",
            "Thatimakulapalle B.O",
            "Thettupalle B.O",
            "Udayamanikyam B.O",
            "Yegavuru B.O",
            "Yerravaripalem B.O",
            "Cheruvumundarapalle B.O",
            "Rangannagarigadda B.O",
            "Thippireddigarialle B.O",
            "Desireddigaripalle B.O",
            "Agraharam B.O",
            "Bandakindapalle B.O",
            "Bodumallulavaripalle B.O",
            "Doddipalle B.O",
            "Ellamanda B.O",
            "Ganugachinta B.O",
            "Gudarevupalle B.O",
            "Jandla B.O",
            "Kondreddigaripalle B.O",
            "Mellacheruvu B.O",
            "Mudupulavemula B.O",
            "Palamgadda B.O",
            "Talupula B.O",
            "Ustikayalapenta B.O",
            "Vadlakunta B.O",
            "Challavaripalle B.O",
            "Jangavandlapalle B.O",
            "Motumallela B.O",
            "Nadimcherla B.O",
            "Vepulabailu B.O",
            "Peddagottigallu B.O",
            "Peddamallela B.O",
            "Merlapaka B.O",
            "Modugulapalem B.O",
            "Panguru B.O",
            "Alimelumangapuram B.O",
            "K.M.Agraharam B.O",
            "Narayanapuram B.O",
            "Ramakrishnapuram B.O",
            "Seetharamapuram B.O",
            "Thimmarajukandriga B.O",
            "Adavikothuru B.O",
            "Gundrajukuppam B.O",
            "Mudipalle B.O",
            "Satravada B.O",
            "Terani B.O",
            "Annur B.O",
            "Chinnadoravarikandriga B.O",
            "Allamadugu B.O",
            "Damodaramaharajapuram B.O",
            "Kathirapalle B.O",
            "Kollagunta B.O",
            "Nochilirajukandriga B.O",
            "Kanduru B.O",
            "Kalikiri Kothapalle B.O",
            "Moorevandlapalle B.O",
            "Nagaripalle B.O",
            "Palamanda B.O",
            "Palem B.O",
            "Regallu B.O",
            "Valligatla B.O",
            "Vootupalle B.O",
            "Errakotapalle B.O",
            "Gundluru B.O",
            "Mudiyamvaripalle B.O",
            "Nawabpet B.O",
            "Thimmapuram B.O",
            "Budithavedu B.O",
            "Gadi B.O",
            "Marrikuntapalle B.O",
            "Nayanicheruvupalle B.O",
            "Pallavolu B.O",
            "Ranganathapuram B.O",
            "T.Sakirevupalle B.O",
            "T.V.Agraharam B.O",
            "Sontyam B.O",
            "Boddapalem B.O",
            "Boyapalem B.O",
            "Chepaluppada B.O",
            "INS Kalinga B.O",
            "J.V.Agraharam B.O",
            "Kapuluppada B.O",
            "Kothaparadesipalem B.O",
            "Peddipalem B.O",
            "Rayapalem B.O",
            "Vellanki B.O",
            "Vemulavalasa B.O",
            "Chinamushidiwada B.O",
            "Chintalapalem B.O",
            "Gandigundam B.O",
            "Gidijala B.O",
            "Gorapalle B.O",
            "Gurrampalem B.O",
            "Gudilova B.O",
            "Pedagadi B.O",
            "Rampuram B.O",
            "Saripalli B.O",
            "V. Juttada B.O",
            "Mindi B.O",
            "Jaggayyapalem B.O",
            "Amanam B.O",
            "Annavaram B.O",
            "Boni B.O",
            "Chippada B.O",
            "Dakamarri B.O",
            "Gudivada B.O",
            "Korada B.O",
            "Majjivalasa B.O",
            "Modavalasa B.O",
            "Mopada B.O",
            "A U Engg College B.O",
            "Pedagadili B.O",
            "Arilova B.O",
            "Dayalnagar B.O",
            "Yendada B.O",
            "Sagar Nagar B.O",
            "Yellapuvanipalem B.O",
            "Narava B.O",
            "Prahladapuram B.O",
            "Durganagar B.O",
            "Venkatapuram B.O",
            "Simhachalam Hills B.O",
            "Porlupalem B.O",
            "Chintalaagaraharam B.O",
            "Yarada B.O",
            "Tunglam B.O",
            "Sheelanagar B.O",
            "Duvvada B.O",
            "Pedamadaka B.O",
            "Pakeertekya B.O",
            "Vedullanarava B.O",
            "Balacheruvu B.O",
            "Gangavaram B.O",
            "Dibbapalem B.O",
            "Nadupuru B.O",
            "Devada B.O",
            "Islampeta B.O",
            "Gandhavaram B.O",
            "Kovvada B.O",
            "Penta B.O",
            "Padmanabham B.O",
            "Kusuluwada B.O",
            "Ananthavaram B.O",
            "Chinnapuram B.O",
            "Gottupalli B.O",
            "Maddi B.O",
            "Potnuru B.O",
            "Sirlapalem B.O",
            "Nagamayyapalem B.O",
            "Nagarapupalem B.O",
            "Pandranki B.O",
            "Polipalli B.O",
            "Ravada B.O",
            "Revidi B.O",
            "Sangivalasa B.O",
            "Singannabanda B.O",
            "Tallavalasa B.O",
            "Tatituru B.O",
            "Gangubudi B.O",
            "Savaravilli B.O",
            "Tummukapalli B.O",
            "Pathabaggam B.O",
            "Buradapeta B.O",
            "Maradam B.O",
            "Sativada B.O",
            "A S Peta B.O",
            "Kallepalli B.O",
            "K R Peta B.O",
            "Kummapalli B.O",
            "Mangalapalem B.O",
            "Bheemali B.O",
            "Ganivada B.O",
            "Kalagada B.O",
            "Kotyada B.O",
            "Nidigattu B.O",
            "Ainada B.O",
            "B.Tallavalasa B.O",
            "Cheluvuru B.O",
            "Chintalavalasa B.O",
            "Jonnada B.O",
            "Malicherala B.O",
            "Raghumanda B.O",
            "Vedullavalasa B.O",
            "Akkivaram B.O",
            "Amatamravivalasa B.O",
            "Bantupalli B.O",
            "Chakivalasa B.O",
            "Gantlam B.O",
            "Kancheru B.O",
            "Mukkam B.O",
            "Munjeru B.O",
            "Nandigam B.O",
            "Madanapuram B.O",
            "Ramabhadrapuram B.O",
            "Regubilli B.O",
            "Revallapalem B.O",
            "Seetharamapuram B.O",
            "Tatipudi B.O",
            "Vasadi B.O",
            "B.Rajeru B.O",
            "Devupalli B.O",
            "Garudabilli B.O",
            "Kanimeraka B.O",
            "Rachakindam B.O",
            "Raindram B.O",
            "Tamatada B.O",
            "Ippalavalasa B.O",
            "Jakkuva B.O",
            "Jayathi B.O",
            "Konda.Lingalavalasa B.O",
            "Kuneru B.O",
            "Uddangi B.O",
            "Pathavalasa B.O",
            "Pindrangi B.O",
            "Relli B.O",
            "Tangudubilli B.O",
            "Uttarapalli B.O",
            "V B Puram B.O",
            "Viyyammapeta B.O",
            "Athava B.O",
            "Golzam B.O",
            "Kallempudi B.O",
            "Khasapeta B.O",
            "Malliveedu B.O",
            "Rangarayapuram B.O",
            "R G Peta B.O",
            "Singarai B.O",
            "Khadarnagar B.O",
            "Gopalapalli B.O",
            "Kottam B.O",
            "Krishnapuram B.O",
            "Madhupada B.O",
            "Talari B.O",
            "Vemulapalli B.O",
            "Bhudevipeta B.O",
            "G Ch Penta B.O",
            "Gollupalem B.O",
            "Jinnam Agrharam B.O",
            "Kenguva B.O",
            "Konisa B.O",
            "Lingalavalasa B.O",
            "Logisa B.O",
            "Madhupada B.O",
            "Marupalli B.O",
            "M Kothavalasa B.O",
            "M Gumudam B.O",
            "Mutcherla B.O",
            "Pedakada B.O",
            "P P Agraharam B.O",
            "S R R Puram B.O",
            "Tummikapalli B.O",
            "Budathanapalli B.O",
            "Korlam B.O",
            "Kotarupalli B.O",
            "Lakkidam B.O",
            "Narava B.O",
            "Neelavathi B.O",
            "Ompalli B.O",
            "Pedavemali B.O",
            "Penasam B.O",
            "P.S.R Puram B.O",
            "Ramavaram B.O",
            "Siripuram B.O",
            "Vasantha B.O",
            "Dharmapuri B.O",
            "Jonnavalasa B.O",
            "Pinavemali B.O",
            "Seetharampuram B.O",
            "Sompuram Agraharam B.O",
            "T Sanduluru B.O",
            "Andra B.O",
            "Garugubilli B.O",
            "G T Peta B.O",
            "Gummakota B.O",
            "Melia Kancheru B.O",
            "Pedaraba B.O",
            "Pittada B.O",
            "Rompalli B.O",
            "Salipeta B.O",
            "Anandapuram B.O",
            "Chintalapeta B.O",
            "Kondagumpam B.O",
            "Mudduru B.O",
            "Parasam B.O",
            "Chodavaram B.O",
            "Damarasingi B.O",
            "Garida B.O",
            "Gujjangivalasa B.O",
            "Jammu B.O",
            "Jarajapupeta B.O",
            "Kella B.O",
            "Kondavelagada B.O",
            "Manyapuripeta B.O",
            "Nagallavalasa B.O",
            "S S R Peta B.O",
            "Tummalapeta B.O",
            "Vallapuram B.O",
            "Ginjeru B.O",
            "Godiyada B.O",
            "J Gumadam B.O",
            "Kirthubarthi B.O",
            "Kondatamarapalli B.O",
            "Kothavalasa B.O",
            "Kothapalem B.O",
            "Veduruvada B.O",
            "Chinakada B.O",
            "Datti B.O",
            "Datti Rajeru B.O",
            "Gadasam B.O",
            "Gobhyam B.O",
            "Gutchimi B.O",
            "Ingilapalli Agraharam B.O",
            "Komatipalli Agraharam B.O",
            "Kompangi B.O",
            "Kuntinivalasa B.O",
            "Pedachamalapalli B.O",
            "Pedamedapalli B.O",
            "Poram B.O",
            "S Chintalavalasa B.O",
            "Vijayaramapuram B.O",
            "Vangara B.O",
            "Vindhyavasi B.O",
            "Alladapalem B.O",
            "Chintapalli B.O",
            "Chodamma Agraharam B.O",
            "Chollangipeta B.O",
            "Govindapuram B.O",
            "Gumpam Agraharam B.O",
            "Kandivalasa B.O",
            "Kanimella B.O",
            "Kg Pathasala B.O",
            "Kovvada Agraharam B.O",
            "Krishnapuram B.O",
            "Kumili B.O",
            "Lankapillipalem B.O",
            "Perapuram B.O",
            "Rellivalasa B.O",
            "Vempadam B.O",
            "Alugolu B.O",
            "A T Agraharam B.O",
            "Boppadam B.O",
            "Gushini B.O",
            "Kothapeta B.O",
            "M J R Peta B.O",
            "Malayada B.O",
            "Ragolu B.O",
            "Saripalli B.O",
            "Tangudubilli B.O",
            "Tatipudi B.O",
            "Valluru B.O",
            "B S Factory B.O",
            "Korukonda B.O",
            "M Kothasvalasa B.O",
            "Ananthagiri B.O",
            "Bheempolu B.O",
            "Boddam B.O",
            "B G Valasa B.O",
            "Gumma B.O",
            "Kasipatnam B.O",
            "K G Budi B.O",
            "Konapuram B.O",
            "Kondiba B.O",
            "Kothuru B.O",
            "Longuparthi B.O",
            "Mallipudi B.O",
            "Muliaguda B.O",
            "Pedabidda B.O",
            "Pedakandepalli B.O",
            "S G Peta B.O",
            "Seethampeta B.O",
            "T B Vara B.O",
            "Timidi B.O",
            "Tokuru B.O",
            "Valasi B.O",
            "Tyda B.O",
            "Veeranaraynam B.O",
            "Y S R Puram B.O",
            "Rakodu B.O",
            "Sarika B.O",
            "Alugubilli B.O",
            "Annamurajupeta B.O",
            "Bhandevpuram B.O",
            "Bheemasinghi B.O",
            "Chinatada B.O",
            "Jaddetivalasa B.O",
            "Jagaram B.O",
            "Pavada B.O",
            "R B Puram B.O",
            "Sasanapalli B.O",
            "Tanavaram B.O",
            "V B Peta B.O",
            "V R Palem B.O",
            "Vizinigiri B.O",
            "Kopperla B.O",
            "Velduru B.O",
            "Garikavalasa B.O",
            "Gudem B.O",
            "Pakirkitthali B.O",
            "Palavalasa B.O",
            "Palli Gandredu B.O",
            "Tatavari Kittali B.O",
            "Tettangi B.O",
            "Kondagandredu B.O",
            "Bhaligattam B.O",
            "Cheepuruvalasa B.O",
            "Denderu B.O",
            "Devada B.O",
            "Banadi B.O",
            "Dabbirajupeta B.O",
            "Gudivada B.O",
            "Nallaballi B.O",
            "N K R Puram B.O",
            "Vavilapadu B.O",
            "Veeluparthi B.O",
            "Ambativalasa B.O",
            "Ayyannapeta B.O",
            "Duppada B.O",
            "Dwarapudi B.O",
            "Gajularega B.O",
            "Gokapeta B.O",
            "Gunkalam B.O",
            "Gotlam B.O",
            "Gunupur B.O",
            "Jammu B.O",
            "Kanapaka B.O",
            "Kondakarakam B.O",
            "Karatam B.O",
            "Munginapalli B.O",
            "Nelivada B.O",
            "Pedathadivada B.O",
            "Pinathadivada B.O",
            "Tekkali B.O",
            "Thotapalem B.O",
            "Gudepuvalasa B.O",
            "Nadupuru B.O",
            "Thimminaidupalem B.O",
            "Pamidimarru B.O",
            "Chinabantupalli B.O",
            "Umamaheswarapuram B.O",
            "Santhiram Medical College B.O",
            "Visweswarayanagar B.O",
            "Arogyavaram B.O",
            "Yadlavanipalem B.O",
            "M L Engg. College B.O",
            "Hindupur Fort B.O",
            "Katakapalli B.O",
            "Marikavalasa B.O",
            "Latchambhavi B.O",
            "Kamalanabhapuram B.O",
            "Gopalapuram B.O",
            "Kondaragolu B.O",
            "Cherukuru B.O",
            "Gangalakurru Agraharam B.O",
            "Chennayapalem B.O",
            "Madakasira Bazaar B.O",
            "Mundy Bazaar B.O",
            "Ramanayyapalem BO",
            "Ramavarappadu SC Colony",
            "R V Nagar B.O",
            "Mettavalasa B.O",
            "Bommuluru B.O",
            "Purimetla B.O",
            "Komanapalle B.O",
            "Nagasamudram B.O",
            "Kollimarla B.O",
            "Nandamurugaruvu B.O",
            "Eddupenta B.O",
            "Koppulavarigudem B.O",
            "Jagannadhapuram B.O",
            "Mandapadu B.O",
            "Chemuduguda B.O",
            "Allur B.O",
            "Thumukunta Industrial Estate B.O",
            "Chintalagudem B.O",
            "Yatapaka B.O",
            "Pulluru PHC B.O",
            "Chintur B.O",
            "Chidumuru B.O",
            "Chatti B.O",
            "Chodavaram B.O",
            "Choppalli B.O",
            "Edurallapalli B.O",
            "Godlagudem B.O",
            "Gogubaka B.O",
            "Gundala B.O",
            "Kolturu B.O",
            "Kommuru B.O",
            "Laxmipuram B.O",
            "Mukunuru  B.O",
            "Purushottapatnam B.O",
            "Tummala B.O",
            "Vegithota B.O",
            "Venakatareddipeta B.O",
            "Mangampadu B.O",
            "Forebey Dam Camp B.O",
            "Tekubaka B.O",
            "Nandigama B.O",
            "Murumuru B.O",
            "Kachavaram B.O",
            "Gannerugoyyapadu B.O",
            "Gannavaram B.O",
            "Chintaregupalli B.O",
            "Jeediguppa B.O",
            "Peddamittapalli B.O",
            "Rekapalli B.O",
            "Sriramagiri B.O",
            "Ummadivaram B.O",
            "Vaddigudem B.O",
            "Abhicherala B.O",
            "Chuchirevulagudem B.O",
            "Kondrajupeta B.O",
            "Kutur B.O",
            "Marrigudem B.O",
            "Pedarkur B.O",
            "Amaravaram B.O",
            "Dachavaram B.O",
            "Damarcherla B.O",
            "Katkuru B.O",
            "Koida B.O",
            "Madhavaram B.O",
            "Ravigudem B.O",
            "Repakagommu B.O",
            "Rudramkota B.O",
            "Sridhar Velair B.O",
            "Thatkuragommu B.O",
            "Tondipaka B.O",
            "Upperu B.O",
            "Velairpadu B.O",
            "Vinjaram B.O",
            "Jarakkonda B.O",
            "Barada B.O",
            "Ginnnelakota B.O",
            "Jamiguda B.O",
            "Poipalli B.O",
            "Durgam B.O",
            "Mettujoru B.O",
            "Hanumpalli B.O",
            "Mulakapalli B.O",
            "Chintalapudi B.O",
            "Garsingi B.O",
            "Pedalochali B.O",
            "Kinchuru B.O",
            "P.Bhimavaram B.O",
            "Kondempudi B.O",
            "Olda B.O",
            "Rapa B.O",
            "Chekumaddila B.O",
            "Ganneruputtu B.O",
            "Andiba B.O",
            "Boddaput B.O",
            "Matyapuram B.O",
            "Laxmipeta B.O",
            "Laxmipuram B.O",
            "Bondapalli B.O",
            "Jarjula B.O",
            "Bungaput B.O",
            "Kagitha B.O",
            "Nellipudi B.O",
            "Pongalipaka B.O",
            "Kavagunta B.O",
            "L Ponnavolu B.O",
            "Jampena B.O",
            "Chintaluru B.O",
            "Gotivada Agraharam B.O",
            "Boyila Kinthada B.O",
            "Timiram B.O",
            "Bennavolu B.O",
            "Adavi Agraharam B.O",
            "Timmannapalem B.O",
            "Kannapalem B.O",
            "Kumada B.O",
            "Injari B.O",
            "Koravangi B.O",
            "Vanagumma B.O",
            "Rngabayalu B.O",
            "Dodiput B.O",
            "Janguluru B.O",
            "Cherlopalem B.O",
            "Bongaram B.O",
            "Bylapudi B.O",
            "D. Suravaram B.O",
            "Gomang B.O",
            "Gulleli B.O",
            "K.J.Puram B.O",
            "Marepalli B.O",
            "Mukundapuram B.O",
            "Polipalli B.O",
            "Tamarabba B.O",
            "V.B.Peta B.O",
            "Gavarapalem B.O",
            "Mangalapuram B.O",
            "Chittayyapalem B.O",
            "Beeram B.O",
            "Valabu B.O",
            "Makavaram B.O",
            "Mettapalem B.O",
            "Bowluwada B.O",
            "R.Bheemavaram B.O",
            "Nagavaram B.O",
            "R.Sivarampuram B.O",
            "Neelakantapuram B.O",
            "Ramavaram B.O",
            "Chadalavada B.O",
            "G.Kothagudem B.O",
            "Pitchukulapadu B.O",
            "Kannaigudem B.O",
            "Ramagopalapuram B.O",
            "Rayanipeta B.O",
            "Regulapadu B.O",
            "Jaggavaram B.O",
            "Lingapuram B.O",
            "Tummileru B.O",
            "Nallakunta B.O",
            "Vissapuram B.O",
            "Karakagudem B.O",
            "Mukundapuram B.O",
            "Modapalli B.O",
            "Thumpada B.O",
            "Gadampalem B.O",
            "Kudumusari B.O",
            "Yerrabommalu B.O",
            "Obulanaidupalem B.O",
            "Vittamrajupalle B.O",
            "Kattuvapalli B.O",
            "Pullayagudem B.O",
            "Bavaipalem B.O",
            "Seetharamanagar B.O",
            "Ganapavaram B.O",
            "Yenduva B.O",
            "Bodamettapalam B.O",
            "Mulakuddu B.O",
            "Mudapaka B.O",
            "Gandhinagar B.O B.O",
            "Ramakrishnapuram B.O",
            "Kellampalli B.O",
            "Kavalakuntla B.O",
            "Pulletikurru S.O",
            "Ravulapalem S.O",
            "Rdo's Office Road S.O",
            "Ryali S.O",
            "Sakhinetipalli S.O",
            "Samanasa S.O",
            "Sivakodu S.O",
            "Tatipaka S.O",
            "Tatipaka Bazar S.O",
            "Vanapalli S.O",
            "Vilasa S.O",
            "Vubalanka S.O",
            "Lakkavaram S.O (East Godavari)",
            "Allavaram S.O",
            "Ambajipeta S.O",
            "Anatavaram S.O",
            "Antarvedipalem S.O",
            "Atreyapuram S.O",
            "Bandarlanka S.O",
            "Bendamurlanka S.O",
            "Bodasakurru S.O",
            "Amalapuram Bus Complex S.O",
            "D.Gannavaram S.O",
            "Gandhi Bazar S.O (East Godavari)",
            "Gopalapuram S.O (East Godavari)",
            "Katrenikona S.O",
            "Kesanakurrupalem S.O",
            "Malikipuram S.O",
            "Moberlypeta S.O",
            "Mori S.O (East Godavari)",
            "Mukkamala S.O",
            "Mukteswaram S.O",
            "Mummidivaram S.O",
            "Nagaram S.O (East Godavari)",
            "New Colony S.O (East Godavari)",
            "Peruru S.O",
            "Ponnamanda S.O",
            "Nakkapalle S.O",
            "Ntpc Simhadri S.O",
            "Nidanam Doddi S.O",
            "Paravada S.O",
            "Payakaraopeta S.O",
            "Pedagummuluru S.O",
            "S Rayavaram S.O",
            "Satyavaram S.O",
            "Subbavaram S.O",
            "Thummapala S.O",
            "Yellamanchili S.O",
            "Araku Colony S.O",
            "Araku Rs S.O",
            "Devarapalli S.O (Visakhapatnam)",
            "G Madugula S.O",
            "Govada S.O",
            "Hukumpeta S.O",
            "Kj Puram S.O",
            "K Kotapadu S.O",
            "A Koduru S.O",
            "Lakkavaram S.O (Visakhapatnam)",
            "Madugula S.O",
            "Paderoo S.O",
            "Pedabayalu S.O",
            "Ravikamatham S.O",
            "Vaddadi S.O",
            "Chintapalli S.O",
            "Kotauratla S.O",
            "Kothakota S.O (Visakhapatnam)",
            "Koyyuru S.O",
            "Krishna Bazar(Narsipatnam) S.O",
            "Kd Peta S.O",
            "Makavarapalem S.O",
            "Nathavaram S.O",
            "Gudem S.O",
            "Sileru Project S.O",
            "Vemulapudi S.O",
            "Atchutapuram S.O",
            "Dimili S.O",
            "Etikoppaka S.O",
            "Gandhinagaram S.O (Visakhapatnam)",
            "Kasimkota S.O",
            "Munagapaka S.O",
            "Georgepet S.O",
            "Kalyandurg S.O",
            "Kalyandurg Bazar S.O",
            "Kambadur S.O",
            "Kandukur S.O",
            "Kuderu S.O (Ananthapur)",
            "Kundurpi S.O",
            "Motilal Street S.O",
            "Narapla S.O",
            "Nuthimadugu S.O",
            "Old Town S.O (Ananthapur)",
            "Patel Road S.O",
            "Putlur S.O",
            "Ramachandra Nagar S.O",
            "Ramnagar S.O (Ananthapur)",
            "Reddivaripalem S.O",
            "Sainagar S.O",
            "Satyanandanagar S.O",
            "Shettur S.O",
            "Singanamala S.O",
            "Ammaladinne S.O",
            "Sri Venkateswara Puram S.O",
            "Tadpatri S.O",
            "Tadpatri Bazar S.O",
            "Tadpatri Bus Stand S.O",
            "Tadpatri Extension S.O",
            "Yellanur S.O",
            "Anantapur Collectorate S.O",
            "Aravindanagar S.O",
            "Anantapur Engg College S.O",
            "Atmakur(ATP) S.O",
            "Belguppa S.O",
            "Bommaganipalli S.O",
            "Bukkarayasamudram S.O",
            "Chukkalur S.O",
            "Gandhibazar S.O (Ananthapur)",
            "Garladinne S.O",
            "Masapet Bazar S.O",
            "Rayachoti S.O",
            "Sambepalli S.O",
            "Veeraballi S.O",
            "Sanjeevi Nagar S.O",
            "Atlur S.O",
            "Chakrapunayanipet S.O",
            "Chitvel S.O",
            "Kodur S.O",
            "Madhavaram S.O (Cuddapah)",
            "Mannur S.O (Cuddapah)",
            "Mantapampalli S.O",
            "Nandalur S.O",
            "Obulavaripalli S.O",
            "Peddarachapalli S.O",
            "Penagalur S.O",
            "Pullampet S.O",
            "Rayavaram S.O (Cuddapah)",
            "Siddavattam S.O",
            "Tangatur S.O",
            "T. Sundupalli S.O",
            "Vontimitta S.O",
            "Rajampet Rs S.O",
            "Kodur Rs S.O",
            "Almaspet S.O",
            "Anantharajupet S.O",
            "Chennur S.O (Cuddapah)",
            "Cuddapah Coop Sugars S.O",
            "Jayanagar S.O (Cuddapah)",
            "Khajipet S.O",
            "Shankarapuram (Cuddapah) S.O",
            "Balathimmayyagaripalli S.O",
            "Cooperative Colony S.O",
            "Lakkireddy Palli S.O",
            "Maruti Nagar S.O",
            "Nagarajupet S.O",
            "Neelakantaraopet S.O",
            "Ravindra Nagar S.O",
            "Sunnapuralla Palli S.O",
            "Yerramukkapalli S.O",
            "Anantharajupuram S.O",
            "Badvel S.O",
            "Badvel Bazaar S.O",
            "Chennampalli S.O",
            "Gopavaram Project Site S.O",
            "Kalasapadu S.O",
            "Kandimallayapalli S.O",
            "Porumamilla S.O",
            "Tekurpet S.O",
            "Chinnamandem S.O",
            "Galiveedu S.O",
            "Pulla S.O",
            "Tadikalapudi S.O",
            "Buttayagudem S.O",
            "Gowrisankara Puram S.O",
            "Jangareddigudem Bazar S.O",
            "Kamavarapukota S.O",
            "Kannapuram S.O",
            "Koyyalagudem S.O",
            "Lakkavaram S.O (West Godavari)",
            "Pedavegi S.O",
            "Jeelugumilli S.O",
            "Ashok Nagar S.O (West Godavari)",
            "Chataparru S.O",
            "Eluru Bus Station S.O",
            "Eluru Collectorate S.O",
            "Gandhinagaram S.O (West Godavari)",
            "Narasimharao Peta S.O",
            "Pathebada S.O",
            "Pedapadu S.O",
            "Ramachandra Rao Peta S.O",
            "Sanivarapu Peta S.O",
            "Sb Colony S.O",
            "Venkata Rao Peta S.O",
            "Vijayarai S.O",
            "Benerjipeta S.O",
            "Denduluru S.O",
            "Eluru Bazar S.O",
            "Eluru R.S S.O",
            "Gopannapalem S.O",
            "Gundugolanu So. S.O",
            "Industrial Estate S.O (West Godavari)",
            "Kovvali S.O",
            "Power Peta S.O",
            "P&t Colony S.O (West Godavari)",
            "Tangellamudi S.O",
            "Westren Street S.O",
            "Chintalapudi S.O",
            "Dharmajigudem S.O",
            "Pragadavaram S.O",
            "T.Narasapuram S.O",
            "Bhimadole S.O",
            "Chebrole S.O (West Godavari)",
            "Dwaraka Tirumala S.O",
            "Kaikaram S.O",
            "Kanumolu S.O",
            "Musunuru S.O",
            "Vidyanagar S.O (Krishna)",
            "Ramanakkapet S.O",
            "Tsanubanda S.O",
            "Vissannapet S.O",
            "Vunguturu S.O (Krishna)",
            "Angaluru S.O",
            "Bantumilli S.O",
            "Elamarru S.O",
            "Golvepalli (Zami) S.O",
            "Janardhanapuram S.O",
            "Kaikalur S.O",
            "Kalidindi S.O",
            "Korukollu S.O",
            "Mandavalli S.O",
            "Manikonda S.O",
            "Moturu S.O",
            "Mudinepalli S.O",
            "Mudunuru S.O",
            "Pedamaddali S.O",
            "Pedagonnuru S.O",
            "Pallevada S.O",
            "Rudrapaka S.O",
            "Satyanarayanapuram S.O (Gudivada)",
            "Tamirisa S.O",
            "Ventrapragada S.O",
            "Gudivada Railway Station S.O",
            "Rajendranagar Colony S.O",
            "Dum Dum Gardens S.O",
            "Gollapalli S.O (Krishna)",
            "Gandhinagaram S.O (Gudivada)",
            "Hanuman Junction S.O",
            "Indupalli S.O",
            "Amidyaya S.O",
            "Gooty S.O",
            "Gooty Bazaar S.O",
            "Gooty R.S. S.O",
            "Gummaghatta S.O",
            "Guntakal Market S.O",
            "Hanumesh Nagar S.O",
            "Herial S.O",
            "Kallur R.S. S.O",
            "Kanekal S.O",
            "Konakondla S.O",
            "Kothapeta(Uravakonda) S.O",
            "Modinabad S.O",
            "Old Guntakal S.O",
            "Pamidi S.O",
            "Pedda Vadagur S.O",
            "Railway Colony S.O (Ananthapur)",
            "Rajendra Nagar S.O (Ananthapur)",
            "Rayadurg S.O",
            "Rayalacheruvu S.O",
            "Tarimala S.O",
            "Timmanacharla S.O",
            "Udegolam S.O",
            "Uravakonda S.O",
            "Vajrakarur S.O",
            "Vidapanakal S.O",
            "Yadiki S.O",
            "Rayadurg  Bazar S.O",
            "Choutra(Guntur) S.O",
            "Chowdaripeta(Guntur) S.O",
            "College Road(Guntur) S.O",
            "Factories Ward S.O",
            "Govt. General Hospital S.O",
            "Kakumanu S.O",
            "Municipal Office(Guntur) S.O",
            "Nehru Nagar(Guntur) S.O",
            "Old Guntur S.O",
            "Pedanandipadu S.O",
            "Prathipadu S.O (Guntur)",
            "Railpet(Guntur) S.O",
            "S.K.P.Temple(Guntur) S.O",
            "S.V.N.Colony(Guntur) S.O",
            "Ponnekallu S.O",
            "Amaravathi S.O",
            "Apsp Colony(Mangalagiri) S.O",
            "K.C.Works S.O",
            "Lemalle S.O",
            "Mangalagiri Bazar S.O",
            "Mangalagiri Busstand S.O",
            "Nagarjuna Nagar S.O",
            "Namburu S.O",
            "Nutakki S.O",
            "Old Mangalagiri S.O",
            "Pedakakani S.O",
            "Pedavadlapudi S.O",
            "Polakampadu Ind. Area S.O",
            "Tadepalle S.O",
            "Tadikonda S.O",
            "Tulluru S.O",
            "Pedapalem S.O",
            "Kothapeta(Guntur) S.O",
            "Guntur Bazar S.O",
            "Guntur Collectorate S.O",
            "Pattabhipuram(Guntur) S.O",
            "Chandramoulinagar S.O",
            "Abbineniguntapalem S.O",
            "Amaravathi Road(Guntur) S.O",
            "A.T.Agraharam(Guntur) S.O",
            "Brodipet(Guntur) S.O",
            "Donka Road(Guntur) S.O",
            "Etukuru S.O",
            "Etukuru Road(Guntur) S.O",
            "Guntur Medical College S.O",
            "Industrial Estate S.O (Guntur)",
            "Koritepadu(Guntur) S.O",
            "L.W.Works(Guntur) S.O",
            "Trunk Road(Guntur) S.O",
            "Bus Stand(Guntur) S.O",
            "Talupula S.O",
            "Tanakallu S.O",
            "Kutagulla S.O",
            "Medapuram S.O",
            "Mudigubba S.O",
            "Nallacheruvu S.O",
            "Agali S.O (Ananthapur)",
            "Amarapuram S.O",
            "Budili S.O",
            "Chennekothapalli S.O",
            "Chilamathur S.O",
            "Gorantla S.O",
            "Gudibanda S.O (Ananthapur)",
            "Guttur S.O",
            "Hemavathi S.O",
            "Hindupur Extns S.O",
            "Hindupur Sevamandir S.O",
            "Kallumarri S.O",
            "Kirikera S.O",
            "Obula Devara Cheruvu S.O",
            "Pamudurthi S.O",
            "Patnam S.O",
            "Perur S.O (Ananthapur)",
            "Prasanthinilayam S.O",
            "Tadimarri S.O",
            "Kodikonda S.O",
            "Lepakshi S.O",
            "Madakasira S.O",
            "Neelakantapuram S.O",
            "Parigi S.O",
            "Peddamanthur S.O",
            "Penukonda S.O",
            "Penukonda Fort S.O",
            "Rallahalli S.O",
            "Roddam S.O",
            "Rolla S.O",
            "Somandepalli S.O",
            "Amadagur S.O",
            "Bathalapalli S.O",
            "Bukkapatnam S.O",
            "Clock Tower Kadiri S.O",
            "Dharmavaram Bazar S.O",
            "Dharmavaram R.S S.O",
            "Gandlapenta S.O",
            "Kadiri S.O",
            "Kadiri Chowk S.O",
            "Kanaganapalli S.O",
            "Kondakamarla S.O",
            "Kothacheruvu S.O",
            "Krishnapuram S.O (Ananthapur)",
            "Nagayalanka S.O",
            "Nidumolu S.O",
            "Nimmakuru S.O",
            "Pamarru S.O (Krishna)",
            "Pamarru Bazar S.O",
            "Pedakallepalli S.O",
            "Pedasanagallu S.O",
            "Polavaram(K) S.O",
            "Balaramunipet S.O",
            "Batchupet S.O",
            "Bhaskarapuram S.O",
            "Brahmapuram S.O",
            "Buttaipet S.O",
            "Chilakalapudi S.O",
            "Chintaguntapalem S.O",
            "Desaipet S.O",
            "Dt.Court S.O",
            "Dokiparru S.O",
            "Godugupet S.O",
            "Gudlavalleru S.O",
            "Inagudurupet S.O",
            "Kavutaram S.O",
            "K.P.Pur S.O",
            "Malakapatnam S.O",
            "Munjuluru S.O",
            "Pedana S.O",
            "Pedanabazar S.O",
            "Rajupet S.O",
            "Challapalli S.O",
            "U.G.C.Works S.O",
            "Valandapalem S.O",
            "Gandhikshetram S.O",
            "Ghantasala S.O",
            "Guduru S.O",
            "Kaja S.O",
            "Kodali S.O",
            "Koduru S.O",
            "K.P.Centre S.O",
            "Lakshmipuram S.O (Krishna)",
            "Mopidevi S.O",
            "Movva S.O",
            "Sanjeeva Nagar S.O",
            "Santajutur S.O",
            "Sirvel S.O",
            "Srinivasa Nagar S.O",
            "Tekke S.O",
            "Thimmapuram S.O",
            "Yallur S.O",
            "Yerraguntla S.O (Kurnool)",
            "N.G.O.S Colony S.O",
            "Ardhaveedu S.O",
            "Besthavari  Peta S.O",
            "Cumbum S.O (Prakasam)",
            "Cumbum East S.O",
            "Akumalla S.O",
            "Banaganapalle S.O",
            "Banaganapalle South S.O",
            "Chagalamarri S.O",
            "Dornipadu S.O",
            "Illuri Kotha Peta S.O",
            "Koilakuntla Bus Stand S.O",
            "Koilakuntla S.O",
            "Kolimigundla S.O",
            "Allagadda MDG S.O",
            "M.V. Nagar S.O",
            "Nossam S.O",
            "Owk S.O",
            "Perusomula S.O",
            "Rudravaram S.O",
            "Sanjamala S.O",
            "Uyyalawada S.O",
            "Bandi Atmakur S.O",
            "Gajulapalle S.O",
            "Industrial Estate S.O (Kurnool)",
            "Tarlupadu S.O",
            "Tokapalle S.O",
            "Tripurantakam S.O",
            "Thummalacheruvu S.O",
            "Thurimella S.O",
            "Vemulakota S.O",
            "Donakonda R.S. S.O",
            "Dupadu S.O",
            "Edavalli S.O",
            "Erragondapalem S.O",
            "Gajjalakonda S.O",
            "Giddalur S.O",
            "Giddalur Bazar S.O",
            "Giddalur West S.O",
            "Komarole S.O",
            "Markapur Bazar S.O",
            "Markapur East S.O",
            "Mohiddin Puram S.O",
            "Mundlapadu S.O",
            "Pedda Dornala S.O",
            "Pitikayagulla S.O",
            "Pullala Cheruvu S.O",
            "Racherla S.O",
            "Rajupalem S.O (Prakasam)",
            "Ravipadu S.O (Prakasam)",
            "Kanala S.O",
            "Nandivargam S.O",
            "Nandyal Bazar S.O",
            "Nandyal R.S. S.O",
            "Noone Palle S.O",
            "Panem S.O",
            "Polur S.O (Kurnool)",
            "Allur S.O",
            "Gandavaram S.O",
            "Kodavaluru S.O",
            "Kavali Cutchery S.O",
            "Siddanakonduru S.O",
            "Seetaramapuram S.O",
            "Udayagiri S.O (Nellore)",
            "Varikuntapadu S.O",
            "Vinjamur S.O",
            "Anantasagaram S.O",
            "Dargamitta S.O",
            "Kovur S.O",
            "Kovur Cutchery S.O",
            "Northrajupalem S.O",
            "Vidavalur S.O",
            "Bitragunta S.O",
            "Chakalakonda S.O",
            "Kavali Co-op Colony S.O",
            "Dagadarthi S.O",
            "Damavaram S.O",
            "Duthalur S.O",
            "Gandipalem S.O",
            "Jaladanki S.O",
            "Janathapeta S.O",
            "Kaligiri S.O",
            "Kondapuram S.O (Nellore)",
            "Nandipadu S.O",
            "Atmakur (NL) S.O",
            "Anumasamudrampeta S.O",
            "Gumparlapadu S.O",
            "Karatampadu S.O",
            "Marripadu S.O",
            "Revur S.O",
            "Sangam S.O",
            "Somasila Project S.O",
            "A.C.Nagar S.O",
            "Andhrakesari Nagar S.O",
            "Balajinagar S.O",
            "Dcbc S.O",
            "Fathekhanpeta S.O",
            "Mulapeta S.O",
            "Nellore Bazar S.O",
            "Pogathota S.O",
            "Anemadugu S.O",
            "Kavali Bazar S.O",
            "Polytechnic S.O (Nellore)",
            "Ramalingapuram S.O",
            "Ranganayakulapeta S.O",
            "Stonehousepet S.O",
            "Trunk Road S.O (Nellore)",
            "Vedayapalem S.O",
            "Brahmadevam S.O",
            "Indukurpeta S.O",
            "Buchireddypalem S.O",
            "Duvvur S.O (Nellore)",
            "Muthukur S.O",
            "Mypadu S.O",
            "Thotapalliguduru S.O",
            "Garugubilli S.O",
            "Gummalakshmipuram S.O",
            "Jagannadhapuram S.O",
            "Komarada S.O",
            "Kurupam S.O",
            "Merangi S.O",
            "Mondemkhallu S.O",
            "Mrutyunjayarayanagaram S.O",
            "Neelanagaram S.O",
            "Palakonda S.O",
            "Parvatipuram Bus Stand S.O",
            "Parvatipuram Town S.O",
            "Pedabondapalli S.O",
            "Ravivalasa S.O",
            "Seethampeta S.O",
            "Seetharampuram Inam S.O",
            "Veeraghattam S.O",
            "Balijipeta S.O",
            "Bobbili Bazar S.O",
            "Bobbili Govt.Hospital Road S.O",
            "Chipurupalle S.O",
            "Donkinavalasa S.O",
            "Garbham S.O",
            "Makkuva S.O",
            "Mamidipalle S.O",
            "Mettapalli S.O",
            "Pachipenta S.O",
            "Piridi S.O",
            "Ramabhadrapuram S.O",
            "Salur Fort S.O",
            "Salur S.O",
            "Seethanagaram S.O",
            "Shreeramnagar S.O",
            "Shreeramnagar Ind.Colony S.O",
            "Therlam S.O",
            "Uttaravalli S.O",
            "Nallajerla S.O",
            "Nidadavole S.O",
            "Nidadavole O.T. S.O",
            "P.N.Kolanu S.O",
            "Pentapadu S.O",
            "Pippara S.O",
            "Polavaram S.O",
            "Pothavaram S.O",
            "Prattipadu S.O",
            "Pmmarket S.O",
            "RTC Bustand(kovvur S.O",
            "Ramnagar S.O (West Godavari)",
            "Samisragudem S.O",
            "Subbaraopeta S.O",
            "Tadimalla S.O",
            "Tallapudi S.O",
            "Tadepalligudem Town S.O",
            "Tadepalligudem Bazar S.O",
            "Vegeswarapuram S.O",
            "Vunguturu S.O (West Godavari)",
            "West Vipparru S.O",
            "Yandagandi S.O",
            "Madhavaram S.O (West Godavari)",
            "Aphb Colony S.O",
            "Ananthapallli S.O",
            "Basivireddipeta S.O",
            "Ch.Agraharam S.O",
            "Chagallu S.O",
            "Devarapalli S.O (West Godavari)",
            "Dondapudi S.O",
            "Duvva S.O",
            "Ganapavaram S.O (West Godavari)",
            "Gopalapuram S.O (West Godavari)",
            "Gowtaminagar S.O",
            "Kakaraparru S.O",
            "Kanuru S.O",
            "Kovvur Old  Town S.O",
            "Appikatla S.O",
            "Chandole S.O",
            "Chebrole S.O (Guntur)",
            "Cheruvu S.O",
            "Intur S.O",
            "Karlapalem S.O",
            "Machavaram S.O (Tenali)",
            "Nidubrole S.O",
            "Patsalatadiparru S.O",
            "Ponnur S.O",
            "Ponnur Bazar S.O",
            "Railpeta Bapatla S.O",
            "Rangaraothota S.O",
            "Snpagraharam S.O",
            "Stuvartpuram S.O",
            "Tsunduru S.O",
            "Turumella S.O",
            "Nizampatnam S.O",
            "Amartaluru S.O",
            "Bhattiprolu S.O",
            "Cherukupalle S.O",
            "Chodayapalem S.O",
            "Dhulipudi S.O",
            "Isukapalle S.O",
            "Kanagala S.O (Guntur)",
            "Kolluru S.O",
            "Kuchinapudi S.O",
            "Kuchipudi S.O",
            "Nagaram S.O (Guntur)",
            "Railpeta - Repale S.O",
            "Vellaturu S.O",
            "Vemuru S.O",
            "Anantavaram S.O",
            "Angalakudur S.O",
            "Duggirala S.O",
            "Emani S.O",
            "Gandhinagar S.O (Guntur)",
            "Ithanagar S.O",
            "Kolakaluru S.O",
            "Kollipara S.O",
            "Kothapeta S.O (Guntur)",
            "Morrispeta S.O",
            "Nandivelugu S.O",
            "Pinapad Tenali S.O",
            "Sangamjagarlamudi S.O",
            "Satyanarayanapuram S.O (Guntur)",
            "Tenali Bazar S.O",
            "Wahabchowk-tenali S.O",
            "Bhavani Nagar S.O",
            "Jagannathapuram S.O",
            "Kapilateertham Road S.O",
            "Korlagunta S.O",
            "Papanaidupet S.O",
            "Renigunta S.O",
            "Settipalli S.O",
            "Tirupati Bazar S.O",
            "Tirupati East S.O",
            "Tiruchanoor Road S.O",
            "Tirupati North S.O",
            "Tirupati South S.O",
            "Vadamalpet S.O",
            "Kattakindavenkatapuram S.O",
            "Pachikapallam S.O",
            "Perumallapalle S.O",
            "R.S.Gardens S.O",
            "S.V.Nagar S.O",
            "S.V.Medical College S.O",
            "S.V.University S.O",
            "Tiruchanoor S.O",
            "Tirumala S.O (Chittoor)",
            "Tirupati West S.O",
            "Chandragiri Fort S.O",
            "Narasingapuram S.O (Chittoor)",
            "Pakala S.O",
            "Bhakarapet S.O",
            "Chinnagottigallu S.O",
            "Damalacheruvu S.O",
            "Gyarampalle-kothapalle S.O",
            "Kallur S.O (Chittoor)",
            "Mangalampet S.O",
            "Nehru Bazar (Piler) S.O",
            "Piler S.O",
            "Rompicherla S.O (Chittoor)",
            "Cherlopalle S.O",
            "Chintaparthi S.O",
            "Gurramkonda S.O",
            "Kalakada S.O",
            "Kalikiri S.O",
            "Mahal S.O (Chittoor)",
            "Medikurthi S.O",
            "Tarigonda S.O",
            "Vayalpad S.O",
            "Pallam S.O",
            "Yerpedu S.O",
            "Sri Bommarajapuram S.O",
            "Ekambarakuppam S.O",
            "Karvetinagar S.O",
            "Nagalapuram S.O (Chittoor)",
            "Nindra S.O",
            "Nagari S.O",
            "Narayanavaram S.O",
            "Pannur S.O (Chittoor)",
            "Puttur S.O",
            "Pissatur S.O",
            "Puttur South S.O",
            "Vepagunta S.O (Chittoor)",
            "Akkurthi S.O",
            "Kothapet (Srikalahasti) S.O",
            "Kovanur S.O",
            "Panagal S.O",
            "Peddakannali S.O",
            "Satyavedu S.O",
            "Srikalahasti North S.O",
            "Thondamanadu S.O",
            "Varadaiahpalem S.O",
            "Gandhigram S.O (Visakhapatnam)",
            "Malkapuram S.O",
            "Gajuwaka S.O",
            "B H P V S.O",
            "Vadlapudi S.O",
            "Pedagantyada S.O",
            "Ukkunagaram S.O",
            "Visakhapatnam Steel Project S.O",
            "Pendurthy S.O",
            "Chittivalasa S.O",
            "Bheemunipatnam S.O",
            "R P Agraharam S.O",
            "Akkayyapalem S.O",
            "Andhra University S.O",
            "Maharanipeta S.O",
            "L B Colony S.O",
            "H B Colony S.O",
            "Dabagardens S.O",
            "Govt Dairy Farm S.O",
            "Visalakshinagar S.O",
            "Pothinamallayapalem S.O",
            "Salagramapuram S.O",
            "P & T Colony (VM) S.O",
            "Visakhapatnam Port S.O",
            "Gitam Engg. College S.O",
            "Kancharapalem S.O",
            "Industrial Estate S.O (Visakhapatnam)",
            "Marripalem S.O",
            "N A D S.O",
            "Gopalapatnam S.O",
            "R R V Puram S.O",
            "Simhachalam S.O",
            "Vepagunta S.O (Visakhapatnam)",
            "Naval Base S.O",
            "Zinc Smelter P S.O",
            "Alamanda R S S.O",
            "Apsp Quarters S.O",
            "Bhogapuram S.O",
            "Bonangi S.O",
            "Bondapalli S.O",
            "Challapeta S.O",
            "Dasannapeta S.O",
            "Dharmavaram S.O",
            "Gajapathinagaram S.O",
            "Gantyada S.O",
            "Industrial Estate S.O (Vizianagaram)",
            "Jami S.O",
            "Kotagandredu S.O",
            "Kothapeta S.O (Vizianagaram)",
            "Kothavalasa S.O",
            "L Kota S.O",
            "Mentada S.O",
            "Moida S.O",
            "Nellimarla S.O",
            "Pedamajjipalem S.O",
            "Pedamanapuram S.O",
            "Pusapatirega S.O",
            "Ramathirtam S.O",
            "Ss Korukonda S.O",
            "S Kota S.O",
            "Vepada S.O",
            "Vizianagaram Collectorate S.O",
            "Vizianagaram Contonment S.O",
            "Vizianagaram City S.O",
            "Vizianagaram Market S.O",
            "Vizianagaram Court Complex S.O",
            "Vzm R.S S.O",
            "Nivagam S.O",
            "P.S.Puram S.O",
            "Bontalakoduru S.O",
            "Calingapatnam S.O",
            "Gara S.O",
            "Gujarathipeta S.O",
            "J.R.Puram S.O",
            "Murapaka S.O",
            "Ponduru S.O",
            "Pydibheemavaram S.O",
            "Rajam S.O",
            "S.R.Puram S.O",
            "S.M.Puram S.O",
            "Sigadam S.O",
            "Srikurmam S.O",
            "Srikakulam Zilla Parishad S.O",
            "Srikakulam Collectorate S.O",
            "Srikakulam Town S.O",
            "Srikakulam Market S.O",
            "Srikakulam District Court S.O",
            "Srikakulam New Colony S.O",
            "Srikakulam Official Colony S.O",
            "Arasavilli S.O",
            "Battili S.O",
            "Burja S.O",
            "Dusi Rs S.O",
            "Hiramandalam S.O",
            "Korasavada S.O",
            "Kotturu S.O",
            "L.N.Peta S.O",
            "Narasannapeta Market S.O",
            "Vunukuru S.O",
            "Budithi S.O",
            "Jalumuru S.O",
            "Mukhalingam S.O",
            "Narasannapeta S.O",
            "Polaki S.O",
            "Priyagraharam S.O",
            "Saravakota S.O",
            "Tilaru RS S.O",
            "Urlam S.O",
            "Akkupalli S.O",
            "Baruva S.O",
            "Baruva R S S.O",
            "Brahmanatarla S.O",
            "Chapara S.O",
            "Haripuram S.O",
            "Ichchapuram S.O",
            "Ichchapuram Bus Stand S.O",
            "Kanchili S.O",
            "Kasibugga S.O (Srikakulam)",
            "Kaviti S.O",
            "Kotabommali S.O",
            "Mandasa S.O",
            "Manikyapuram S.O",
            "Ms Palli S.O",
            "Meliaputti S.O",
            "Naupada S.O (Srikakulam)",
            "Naupada RS S.O",
            "Palasa S.O",
            "Pundi R S S.O",
            "Sompeta S.O",
            "Pathapatnam S.O",
            "Central Prison B.O",
            "Gummalladibba B.O",
            "Penumudi B.O",
            "Diguvamagham B.O",
            "Eachaneri B.O",
            "Gazualapalle B.O",
            "Peddayellampalli B.O",
            "Gopapuram B.O",
            "Gudipudiagraharam B.O",
            "Marripudi B.O",
            "Iteru B.O",
            "Poondla B.O",
            "Bhavanamvaripalem B.O",
            "Bhoolayapalem B.O",
            "Koduru-komali B.O",
            "Sangupalem B.O",
            "Vellaluru B.O",
            "Kovelamudi B.O",
            "Lemellepadu B.O",
            "Vatticheruku B.O",
            "Lingamguntlapalem B.O",
            "Manchala B.O",
            "Mutluru B.O",
            "Narakoduru B.O",
            "Godavarru B.O",
            "Gundavaram B.O",
            "Jupudi B.O",
            "Kothareddypalem B.O",
            "Pathareddypalem B.O",
            "Brahmanakoduru B.O",
            "Gollamudipadu B.O",
            "Kothapalli-narikellapalli B.O",
            "Srirangapuram B.O",
            "Vetapalem B.O",
            "Khajipalem B.O",
            "Peddapalle B.O",
            "Siripudi B.O",
            "Manthenavaripalem B.O",
            "Nindali B.O",
            "Mettu B.O",
            "Karaballavolu B.O",
            "Tikkavaram B.O",
            "Kolanukuduru B.O",
            "Kanupuru B.O",
            "Beripeta B.O",
            "Errandlapalle B.O",
            "Jambuvaripalle B.O",
            "K.G. Satram B.O",
            "Karidirivaripalle B.O",
            "Katappagaripalle B.O",
            "Managalapalle B.O",
            "Muthukuru B.O",
            "Nalagampalle B.O",
            "Thumabakuppam B.O",
            "Thambuganipalle B.O",
            "Thumba B.O",
            "Gollapalle B.O",
            "Kattakindapalle B.O",
            "Madhavaram B.O",
            "Mallakunta B.O",
            "Pedda Kowkuntla B.O",
            "Raketla B.O",
            "Nimbagallu B.O",
            "Gootyanantapur B.O",
            "Isurallapalli B.O",
            "Brahmanapalli B.O",
            "Gollaladoddi B.O",
            "Yamarru B.O",
            "Ananthavarappadu B.O",
            "Mathyam B.O",
            "Pallecheruvu B.O",
            "Putramaddi B.O",
            "Sadakuppam B.O",
            "Sarakallu B.O",
            "Vengampalle B.O",
            "Todatara B.O",
            "Cherlopalle B.O",
            "Pantrampalle B.O",
            "Tenebanda B.O",
            "T. Savatapalle B.O",
            "Ialavaripalle B.O",
            "Nampalle B.O",
            "Polakala B.O",
            "Pullur B.O",
            "Yellampalle Santhagate B.O",
            "Yerrepalle B.O",
            "Diguvatadakara B.O",
            "Kothapalle B.O",
            "Paipalle B.O",
            "Patnam B.O",
            "Puthur B.O",
            "Thavanampalle B.O",
            "Uttarabrahmanapalle B.O",
            "Chalamangalam B.O",
            "Pedapulipaka B.O",
            "Ammireddigudem B.O",
            "Dandapalle B.O",
            "Kalagatur B.O",
            "Neerugattuvaripalle B.O",
            "Horsely Hills B.O",
            "Arlapadu B.O",
            "Erramadu B.O",
            "Gosavedu B.O",
            "Gullapudi B.O",
            "Yelloti B.O",
            "Ellampalle Kothuru B.O",
            "Erlampalle B.O",
            "Govindareddipalle B.O",
            "Kanumuru B.O",
            "Kothapalli B.O",
            "Vinagadapa B.O",
            "Thotapalli B.O",
            "Vattigudipadu B.O",
            "Kantakapalli B.O",
            "Alamanda Sandy B.O",
            "Gurla B.O",
            "Dasulapalem B.O",
            "Pasupam B.O",
            "Pathivada B.O",
            "Raghudevapuram B.O",
            "Pasalapudi B.O",
            "Chinaogirala B.O",
            "Kunderu B.O",
            "Pedaogirala B.O",
            "Nepalli B.O",
            "Gudimetla B.O",
            "Kasarabad B.O",
            "Konayapalem B.O",
            "Kodavatikallu B.O",
            "Pokkunuru B.O",
            "Popuru B.O",
            "Punnavalli B.O",
            "Veladikothapalem B.O",
            "Kalavapamula B.O",
            "Ilaprolu B.O",
            "Kavuluru B.O",
            "Pinapaka B.O",
            "Ida Kondaplli B.O",
            "Muktyala B.O",
            "Vedadri B.O",
            "Vanukuru B.O",
            "Edupugallu B.O",
            "Chintalanerva B.O",
            "Duggiralapadu B.O",
            "Konijerla B.O",
            "Nemali B.O",
            "Vutukuru B.O",
            "Ambapuram B.O",
            "Bandarugudem B.O",
            "Chiravada B.O",
            "Satyalapadu B.O",
            "Tunikipadu B.O",
            "Galigopuram B.O",
            "Suravaram B.O",
            "Chintalapadu B.O",
            "Kokilampadu B.O",
            "Kommireddipalli B.O",
            "Lakshmipuram B.O",
            "Mallela B.O",
            "Munukulla B.O",
            "Rolupadu B.O",
            "Sriniketan B.O",
            "Vamukuntla B.O",
            "Vavilala B.O",
            "Kondurupadu B.O",
            "Rajagopalapuram B.O",
            "Rangannagudem B.O",
            "Remalle B.O",
            "Veleru B.O",
            "Devarapalli B.O",
            "Avidi B.O",
            "Chirata Pudi B.O",
            "Kedarlanka B.O",
            "Vadapalem B.O",
            "Yenugulamahal B.O",
            "Appanapalli B.O",
            "Manepalli B.O",
            "Modekurru B.O",
            "Narendrapuram B.O",
            "Udamalakudithi B.O",
            "Tirumala Kuppam B.O",
            "Bandapalle B.O",
            "Chinnaickenpalle B.O",
            "Doddipalle B.O",
            "Kalavagunta B.O",
            "Kattmanchi B.O",
            "Kotrakona B.O",
            "Muthireval B.O",
            "Poonepallekandriga B.O",
            "Sathambakkam B.O",
            "Vavilthota B.O",
            "Akanambattu B.O",
            "Baitapalle B.O",
            "Chinnakalikiri B.O",
            "Erracheruvupalle B.O",
            "Kammguttapalle B.O",
            "Mudigolam B.O",
            "Palakur B.O",
            "Patoor B.O",
            "Polavaram B.O",
            "Deenabandupuram B.O",
            "Matavalam B.O",
            "Palasamudram B.O",
            "Siddarajurangarajukandiga B.O",
            "Simharajapuram B.O",
            "Srikaverirajapuram B.O",
            "Vanadurgapurambo B.O",
            "Vemavaram B.O",
            "Thalupulapalle B.O",
            "Vajjireddipalle B.O",
            "Tenepalle B.O",
            "Pasalapudi B.O",
            "Kondayapalem B.O",
            "Cheruvukommupalem B.O",
            "Chintalacheruvu B.O",
            "Lingamukkapalle B.O",
            "Mukkellapadu B.O",
            "Murthuzapuram B.O",
            "Nagireddipalle B.O",
            "Kankanalapalle B.O",
            "Mugachintalapalem B.O",
            "Remidicherla B.O",
            "Domalagundam B.O",
            "Gandiganumala B.O",
            "Ravulapuram B.O",
            "Uppalapadu B.O",
            "Achavalli B.O",
            "Ganganapalle B.O",
            "Inagalur B.O",
            "Kondreddypalle B.O",
            "Krishnamgaripalle B.O",
            "Nallacheruvupalle B.O",
            "Palur B.O",
            "Saidapuram B.O",
            "Santhakovur B.O",
            "Udavagandla B.O",
            "Chinnandlur B.O",
            "Chirrajupalle B.O",
            "Illur B.O",
            "Kalamalla B.O",
            "Nidizuvvi B.O",
            "Bhimagundam B.O",
            "M.Kambaladinne B.O",
            "Narjampalle B.O",
            "Nawabpeta B.O",
            "Ponnampalle B.O",
            "Talamanchipatnam B.O",
            "Torrivemmula B.O",
            "Bodithippanapadu B.O",
            "Gundlakunta B.O",
            "Karamalavandlapalle B.O",
            "Ponnathota B.O",
            "S.Uppalapadu B.O",
            "Veparala B.O",
            "Bayanapalle B.O",
            "Chinnasinganapalle B.O",
            "Errapalle B.O",
            "Gudipadu B.O",
            "Idamadaka B.O",
            "Jillella B.O",
            "Kamanur B.O",
            "Kanagudur B.O",
            "Krishnampalle B.O",
            "Machanapalle B.O",
            "Madirepalle B.O",
            "Neelapuram B.O",
            "Nelatur B.O",
            "Peddajonnavaram B.O",
            "Pullareddypeta B.O",
            "Ramapuram B.O",
            "Ramasainagar B.O",
            "T.Sallabasayapalle B.O",
            "Vasudevapuram B.O",
            "Venkupalle B.O",
            "Karnapapayapalle B.O",
            "Gondipalle B.O",
            "Rudrampeta B.O",
            "Brahma Samudram B.O",
            "Mulakaledu B.O",
            "Appa Rao Street B.O",
            "Kanakaveedu B.O",
            "Machapuram B.O",
            "Pulichinta B.O",
            "Banavasi B.O",
            "Erramattam B.O",
            "Guvvalakunta B.O",
            "T Samala Gudur B.O",
            "Alebad B.O",
            "Boyanacheruvupalle B.O",
            "Burugula B.O",
            "Garladinne B.O",
            "Kommemarri B.O",
            "Nereducherla B.O",
            "Racherla B.O",
            "Utakonda B.O",
            "Pasupula B.O",
            "Laddagiri B.O",
            "Chanugondla B.O",
            "Krishna Puram B.O",
            "Kurunur B.O",
            "Mudamalakurthi B.O",
            "Pyalakurthi B.O",
            "Varkur B.O",
            "Venkatagiri B.O",
            "Bijina Vemula B.O",
            "Mutsumarri B.O",
            "Nehru Nagar B.O",
            "Kalugotla B.O",
            "Krishnapuram B.O",
            "M.Pendakallu B.O",
            "Pullagummi B.O",
            "Sarparajapuram B.O",
            "S.Boyanapalli B.O",
            "Venkatagiri B.O",
            "Kosanapalle B.O",
            "Serigolvepalli B.O",
            "Pitchikalapalem B.O",
            "Korimerla B.O",
            "Chinavenkannapalem B.O",
            "Kandulur B.O",
            "Karumanchi B.O",
            "Konizedu B.O",
            "Mallavarappadu B.O",
            "Marlapadu B.O",
            "Pellur B.O",
            "Savireddi Palem B.O",
            "Thurpu Naidu Palem B.O",
            "Vengamukka Palem B.O",
            "Yerazerla B.O",
            "Vijjeswaram B.O",
            "Surya Rao Palem B.O",
            "Ravipadu B.O",
            "Koduru B.O",
            "Amal College B.O",
            "Navara B.O",
            "D. Ramavaram  B.O",
            "Bobbili R.S B.O",
            "Vantharam B.O",
            "Addapuseela B.O",
            "Jarna B.O",
            "Kommadi B.O",
            "Gayatri Engg College B.O",
            "Gedalavani Palem B.O",
            "Medaram B.O",
            "Narayanapuram B.O",
            "Lingapalem B.O",
            "Isukapudi B.O",
            "Krapa B.O",
            "Kajuluru B.O",
            "Ramesampeta B.O",
            "Cherukumpalem B.O",
            "Ganapavaram B.O",
            "Siddanthipuram B.O",
            "Pullur kottalu B.O",
            "Ravulapalli B.O",
            "Thavaripalli B.O",
            "Tripuravaram B.O",
            "Thudumaladinne B.O",
            "Nerellavalasa B.O",
            "Aitam Engg.College B.O",
            "Kurigam B.O",
            "D. Matchilesam B.O",
            "Purushothapur (IPR) B.O",
            "Bhaggeswaram B.O",
            "A.Vemavaram B.O",
            "Mahanandi B.O",
            "Rajaji Street B.O",
            "Doddanakeri B.O",
            "Kapati B.O",
            "Pesalabanda B.O",
            "Peddahothur B.O",
            "Urukunda B.O",
            "Togarchedu B.O",
            "Goragummi B.O",
            "Dewancheruvu B.O",
            "APHB Colony B.O",
            "Radheyapalem B.O",
            "Tarluvada B.O",
            "Sri krishnapuram B.O",
            "Chittoor Sugarfactory B.O",
            "Madanapalle Spinning Mills Gds B.O",
            "Gangavaram",
            "Vyasasramam B.O",
            "Krishnam Setty Palle B.O",
            "Dommeru B.O",
            "Gutala B.O",
            "Pedaravuru B.O",
            "Vallabharaopalem B.O",
            "Patamata Lanka B.O",
            "Pali Gds B.O",
            "Perecherla B.O",
            "Konada B.O",
            "Parsannayapalli B.O",
            "Rajiv Colony B.O",
            "Pandurangapuram B.O",
            "Kanthinagar B.O",
            "NSTL B.O",
            "Khaderpalle B.O",
            "Kumara Venkata Bhupala Puram B.O",
            "C.Gollapalle B.O",
            "Daminadu B.O",
            "Stantanpuram B.O",
            "B.Tandrapadu B.O",
            "P.Lingapuram B.O",
            "Bantanahalu B.O",
            "Munagalapadu B.O",
            "Mekalabalayapalle B.O",
            "Madhavaram (kurnool)B.O",
            "APSP Xl Batallion B.O",
            "Ukkayapalle B.O",
            "Ramanjaneyapuram B.O",
            "N.Rangapuram B.O",
            "Chinnatekur B.O",
            "Marakattu B.O",
            "Chinna Pendekallu B.O",
            "N.Khairavadi B.O",
            "Aminabad B.O",
            "Kappatralla B.O",
            "Thudicherla B.O",
            "Beldona B.O",
            "Chippagiri B.O",
            "Gummanur B.O",
            "Khajeepuram B.O",
            "Mallikarjunahalli B.O",
            "Ramadurgam B.O",
            "Yeruru B.O",
            "Arekallu B.O",
            "Baichigeri B.O",
            "Basapuram B.O",
            "Dhanapuram B.O",
            "Dibbanakallu B.O",
            "G.Hosanahalli B.O",
            "Isvi B.O",
            "Kamavaram B.O",
            "Kammarchedu B.O",
            "Madhire B.O",
            "Manekurthi B.O",
            "Musanahalli B.O",
            "Peddathumbalam B.O",
            "Buruzula B.O",
            "Chakkaralla B.O",
            "Chandoli B.O",
            "Chinnahulthi B.O",
            "Dudekonda B.O",
            "Hosuru B.O",
            "Jutur B.O",
            "Pandikona B.O",
            "Pulikonda B.O",
            "Putchakayalamada B.O",
            "Ratana B.O",
            "Doddimekala B.O",
            "H.Muravani B.O",
            "Kallukunta B.O",
            "Mekadona B.O",
            "Channampalli B.O",
            "G.Erragudi B.O",
            "Jonnagiri B.O",
            "Kothur B.O",
            "Madananthapuram B.O",
            "Pagidirai B.O",
            "Peravali B.O",
            "Upparlapalli B.O",
            "Daivamdinne B.O",
            "Enigabala B.O",
            "Govt Live Stock Form B.O",
            "Gudikal B.O",
            "Halaharvi B.O",
            "Kadimetla B.O",
            "Kalugotla B.O",
            "Kambadahal B.O",
            "Kambaladinne B.O",
            "Kotekallu B.O",
            "Mugati B.O",
            "Nagaladinne B.O",
            "Parlapalli B.O",
            "Peddakothali B.O",
            "T.Sallakudlur B.O",
            "T.B.P.Colony B.O",
            "Venkatagiri B.O",
            "Billekallu B.O",
            "Muthukur B.O",
            "Virupapuram B.O",
            "Chigali B.O",
            "Basarakodu B.O",
            "Nagaruru B.O",
            "Mantriki B.O",
            "Bairluty B.O",
            "Bhanumukkala B.O",
            "Dudyala B.O",
            "Gokavaram B.O",
            "Indireswaram B.O",
            "Iskala B.O",
            "Karivena B.O",
            "Kothapalli B.O",
            "Kurukunda B.O",
            "M.Lingapuram B.O",
            "Musalimadugu B.O",
            "Nallakalva B.O",
            "Nandikunta B.O",
            "Pinnapuram B.O",
            "Siddapuram B.O",
            "Siddepalli B.O",
            "Sivapuram B.O",
            "Vadlaramapuram B.O",
            "Brahmanadoddi B.O",
            "Gundrevula B.O",
            "Inagandla B.O",
            "Julekallu B.O",
            "Kambadahal B.O",
            "Kondapuram B.O",
            "Mudumala B.O",
            "Palukudoddi B.O",
            "Polukallu B.O",
            "Pulakurthi B.O",
            "Thimmandoddi B.O",
            "Kulumalapalli B.O",
            "Muddavaram B.O",
            "Musalayacheruvu B.O",
            "Sitharampuram B.O",
            "Yembai B.O",
            "Bollavaram B.O",
            "Damagatla B.O",
            "Kollabavapuram B.O",
            "Pudur B.O",
            "Vaddeman B.O",
            "Bugganipalli B.O",
            "Kandikayapalli B.O",
            "Alardinne B.O",
            "Jilledubudakala B.O",
            "Karivemula B.O",
            "Khairuppala B.O",
            "Kunkanur B.O",
            "Nelatalamarri B.O",
            "Nellibanda B.O",
            "Pallidoddi B.O",
            "Ternekallu B.O",
            "Yelamakur B.O",
            "Bogolu B.O",
            "B.Ramadurgam B.O",
            "Chityala B.O",
            "Dharmavaram B.O",
            "Jagadurthi B.O",
            "Kamaganikuntla B.O",
            "Kamalapuram B.O",
            "Katarukonda B.O",
            "Kotchervu B.O",
            "Koilakonda B.O",
            "Malliyala B.O",
            "Malkapuram B.O",
            "Sudepalli B.O",
            "Udumulapadu B.O",
            "Ungaralagundla B.O",
            "Agaveli B.O",
            "Chellelichelimala B.O",
            "Chunchu Erragudi B.O",
            "Kambalapadu B.O",
            "Kotakonda B.O",
            "Krishnagiri B.O",
            "Lakkasagaram B.O",
            "Pothugal B.O",
            "Venkatapuram B.O",
            "Bilakalaguduru B.O",
            "Grandhivemula B.O",
            "Korrapolur B.O",
            "Manchalakatta B.O",
            "Regadigudur B.O",
            "Vanala B.O",
            "Diguvapadu B.O",
            "Masapeta B.O",
            "Kadumur B.O",
            "Kethavaram B.O",
            "Nandanapalli B.O",
            "Pasupula B.O",
            "Padidempadu B.O",
            "Puricherla B.O",
            "Rudravaram B.O",
            "Alavala B.O",
            "Errabadu B.O",
            "G.D.Project B.O",
            "Ganjihalli B.O",
            "H.Khairvadi B.O",
            "Iranbanda B.O",
            "Kulumala B.O",
            "Peddamarriveedu B.O",
            "Peddanelatur B.O",
            "Thippanuru B.O",
            "Gudipadu B.O",
            "Kothakota B.O",
            "Mallapuram B.O",
            "Munagala B.O",
            "R.Kanapuram B.O",
            "Remata B.O",
            "Amadaguntla B.O",
            "A.Gokulapadu B.O",
            "Anugonda B.O",
            "Gorantla B.O",
            "Parla B.O",
            "Salkapuram B.O",
            "S.Erragudi B.O",
            "Ulchala B.O",
            "Erradoddi B.O",
            "Bukkapuram B.O",
            "Dinnedevarapadu B.O",
            "Joharapuram B.O",
            "Loddipalli B.O",
            "Meedivemula B.O",
            "Narnur B.O",
            "Uppalapadu B.O",
            "Vuyyalawada B.O",
            "Edururu B.O",
            "E.Thandrapadu B.O",
            "Gondiparla B.O",
            "G.Singavaram B.O",
            "Mamidalapadu B.O",
            "Nidjur B.O",
            "Panchalingala B.O",
            "R.Konthalapadu B.O",
            "S.R.P.M B.O",
            "Tholisapuram B.O",
            "Cherukucherla B.O",
            "Chowtkur B.O",
            "Chintalapalli B.O",
            "Devanur B.O",
            "Jalakanur B.O",
            "Veepanagandla B.O",
            "Alaganur B.O",
            "Rollapadu B.O",
            "Burandoddi B.O",
            "Yatakallu B.O",
            "Talamudipi B.O",
            "K.Markapuram B.O",
            "Bannuru B.O",
            "Yenugumarri B.O",
            "Bollavaram B.O",
            "Komarole B.O",
            "Sulekeri B.O",
            "Arlabanda B.O",
            "Nagardona B.O",
            "Tangaradona B.O",
            "Ganapuram B.O",
            "Jutur B.O",
            "Malyala B.O",
            "Mandlem B.O",
            "N.S.C.Farm B.O",
            "Parumanchala B.O",
            "Sathanikota B.O",
            "Tangadancha B.O",
            "Tarigopula B.O",
            "Tarturu B.O",
            "Tummalur B.O",
            "Chelimilla B.O",
            "Erraguduru B.O",
            "Mittakandala B.O",
            "Chandrapalli B.O",
            "Chinnapodilla B.O",
            "Devarabanda B.O",
            "Gudipadu B.O",
            "Hussainapuram B.O",
            "Jakkasanikuntla B.O",
            "Kadamakuntla B.O",
            "Kalachatla B.O",
            "Kothakota B.O",
            "Mettupalli B.O",
            "P.R.Palli B.O",
            "Peddapaya B.O",
            "Pothidoddi B.O",
            "Peddapodilla B.O",
            "Sebhaspuram B.O",
            "Vengalampalli B.O",
            "Bondimadugula B.O",
            "Edduladoddi B.O",
            "Gundlakonda B.O",
            "Marella B.O",
            "Mukkella B.O",
            "Nallachelimala B.O",
            "Pendekallu Bus Stand B.O",
            "Rampalli B.O",
            "T.Sanugondla B.O",
            "Biravolu B.O",
            "Pagidala B.O",
            "Prathakota-east B.O",
            "Sankirenipalli B.O",
            "Thatipadu B.O",
            "Balapalapalli B.O",
            "Gutupalli B.O",
            "H.Kottala B.O",
            "R.Kothapalli B.O",
            "Rahimanpuram B.O",
            "Industrial Estate B.O",
            "Kalluru B.O",
            "Peddapadu B.O",
            "Bastipadu B.O",
            "Chatlamallapuram B.O",
            "Konganapadu B.O",
            "L.Polur B.O",
            "Nayakallu B.O",
            "Tadakanapalli B.O",
            "Amakathadu B.O",
            "Bommireddipalli B.O",
            "Cherukulapadu B.O",
            "Govardhanagiri B.O",
            "Lakshminagaram B.O",
            "Mallepalli B.O",
            "N.Venkatapuram B.O",
            "Talla Gokulapadu B.O",
            "Abdullapuram B.O",
            "Banakacherla B.O",
            "Bhojanam B.O",
            "Boyarevula B.O",
            "Guntakandala B.O",
            "Maddur B.O",
            "Madhavaram B.O",
            "Mothukuru B.O",
            "Narayanapauram B.O",
            "P.Devalapuram B.O",
            "Velpanur B.O",
            "Vempenta B.O",
            "Gani B.O",
            "Hussainapuram B.O",
            "Kalva B.O",
            "N.Konthalapadu B.O",
            "Sekunala B.O",
            "Somayajulapalli B.O",
            "Arikera B.O",
            "Bilehalu B.O",
            "Chinnahothur B.O",
            "Ellarthi B.O",
            "Halebidu B.O",
            "Hattibelagallu B.O",
            "Kuruvalli B.O",
            "Molagavalli B.O",
            "Muddanageri B.O",
            "Nerniki B.O",
            "Atikalagundu B.O",
            "Devanabanda B.O",
            "Haligera B.O",
            "Joharapuram B.O",
            "Bapuram B.O",
            "Bevinahal B.O",
            "Chintakunta B.O",
            "Gulyam B.O",
            "Hardageri B.O",
            "Kaminehal B.O",
            "Kokkarchedu B.O",
            "Medehal B.O",
            "Nitravatti B.O",
            "Siddapuram B.O",
            "T.Sakibanda B.O",
            "Chudi B.O",
            "Gudikambali B.O",
            "Katriki B.O",
            "Nadichagi B.O",
            "Chinnahyti B.O",
            "Honnur B.O",
            "Kogilathota B.O",
            "Marlamadiki B.O",
            "Sammatageri B.O",
            "Virupapuram B.O",
            "Chinnaharivanam B.O",
            "Gajjehalli B.O",
            "Harivanam B.O",
            "Hebbatam B.O",
            "Lingadahalli B.O",
            "Naganathanahalli B.O",
            "Santhekudlur B.O",
            "Vandavagili B.O",
            "B.Agraharam B.O",
            "Banavanur B.O",
            "Byluppala B.O",
            "D. Kotakonda B.O",
            "Kandanathi B.O",
            "Karumanchi B.O",
            "Mulagundam B.O",
            "Badinehal B.O",
            "Bapuram B.O",
            "Dommaladinne B.O",
            "Erigeri B.O",
            "Hanavolu B.O",
            "Kuntanahal B.O",
            "Kuppagallu B.O",
            "Roudur B.O",
            "Upparahal B.O",
            "Belagallu B.O",
            "Chirtanakallu B.O",
            "Duddi B.O",
            "Jampapuram B.O",
            "Jummaladinne B.O",
            "Kandukuru B.O",
            "Kaggallu B.O",
            "Sathanur B.O",
            "Vandagallu B.O",
            "Hampa B.O",
            "M.Agraharam B.O",
            "Nancherla B.O",
            "Chinnathumbalam B.O",
            "Malapalli B.O",
            "Om Nagar B.O",
            "Ratsamarri B.O",
            "Sugur B.O",
            "Sunkeswari B.O",
            "Vagarur Thimmapuram B.O",
            "Chatnihalli B.O",
            "Chilakaladona B.O",
            "Ibharampuram B.O",
            "Kalludevakuntla B.O",
            "Peda Modugapalli B.O",
            "Cheemalapadu B.O",
            "Pondugula B.O",
            "Doddadevarapadu B.O",
            "Chavutapalli B.O",
            "Gangapadu B.O",
            "Gollamandala B.O",
            "Kakarla B.O",
            "Keesara B.O",
            "Polisettipadu B.O",
            "Putrela B.O",
            "Ramachandrapuram B.O",
            "Repudi B.O",
            "Rudravaram B.O",
            "Vallampatla B.O",
            "Vemireddipalle B.O",
            "Chevitikallu B.O",
            "Damuluru B.O",
            "Gani Atkuru B.O",
            "Gottumukkala B.O",
            "Jammavaram B.O",
            "Moguluru B.O",
            "Munnaluru B.O",
            "Paritala B.O",
            "Ponnavaram B.O",
            "Hanumanthapuram B.O",
            "Kadavakollu B.O",
            "Jayanthipuram B.O",
            "Atkuru B.O",
            "Chevutur B.O",
            "Cheruvu Madhavaram B.O",
            "Duggiralapadu B.O",
            "Ganginenipalem B.O",
            "Tolukodu B.O",
            "Velvdam B.O",
            "Venkatapuram B.O",
            "Chandapuram B.O",
            "Cheruvukommupalem B.O",
            "Gandepalli B.O",
            "Boddapadu B.O",
            "Peddapuram B.O",
            "Lingagudem B.O",
            "Payakapuram. B.O",
            "Kesarapalli B.O",
            "Zakkulanekkalam B.O",
            "Bobbellapadu B.O",
            "Vibharintapadu B.O",
            "Bandipalem B.O",
            "Bhimavaram B.O",
            "Gowravaram B.O",
            "Konakanchi B.O",
            "Gollamudi B.O",
            "Ithavaram B.O",
            "Jonnalagadda B.O",
            "Kammavaripalem B.O",
            "Konduru B.O",
            "Kanchala B.O",
            "Kethaveerunipadu B.O",
            "Lingalapadu B.O",
            "Magallu B.O",
            "Munagacherla B.O",
            "Nawabpet B.O",
            "Pallagiri B.O",
            "Pendyala B.O",
            "Raghavapuram B.O",
            "Ramireddipalli B.O",
            "Rudravaram B.O",
            "Sanagapadu B.O",
            "Somavaram B.O",
            "Torragudipadu B.O",
            "Vemulapalli B.O",
            "Adavinekkalam B.O",
            "Kanasanapalli B.O",
            "Pathapadu B.O",
            "Surampalli B.O",
            "Atkur B.O",
            "Pottipadu B.O",
            "Tempalli B.O",
            "Veerapanenigudem B.O",
            "Jayanthi B.O",
            "Konathamatmakur B.O",
            "Agniparru B.O",
            "Aminapuram B.O",
            "Choragudi B.O",
            "Krishnapuram B.O",
            "Pamidimukkala B.O",
            "Penumatcha B.O",
            "Gandigunta B.O",
            "Garikiparru B.O",
            "Kanakavalli B.O",
            "Penamakuru B.O",
            "Yakamuru B.O",
            "Kanuru B.O",
            "Vasanthanagar B.O",
            "Yanamalakuduru B.O",
            "Godavarru B.O",
            "Madduru B.O",
            "Manthena B.O",
            "Proddutur B.O",
            "Punadipadu B.O",
            "Royyur B.O",
            "Uppaluru B.O",
            "Gudavalli B.O",
            "Velpuru B.O",
            "Chodavaram B.O",
            "Ganguru B.O",
            "Enikepadu B.O",
            "Kattubadipalem B.O",
            "Pochampalli B.O",
            "Tirumalagiri B.O",
            "Allapuram B.O",
            "Azzampudi B.O",
            "Buthumillipadu B.O",
            "Bahubalendrunigudem B.O",
            "Budhavaram B.O",
            "Chikkavaram B.O",
            "Gopavarapugudem B.O",
            "Gollanapalli B.O",
            "Purushothapatnam B.O",
            "Roynagar B.O",
            "Anumanchipalli B.O",
            "Balusupadu B.O",
            "Budavada B.O",
            "Gandrai B.O",
            "Jami Annavaram B.O",
            "Lime Stone Town Ship B.O",
            "Malkapuram B.O",
            "Shermohammadpet B.O",
            "Srinivasa Nagar Colony B.O",
            "Takkellapadu B.O",
            "Alluru B.O",
            "Chennaraopalem B.O",
            "Dachavaram B.O",
            "Gudem Madhavaram B.O",
            "Kontalapalli B.O",
            "Narasimharaopalem B.O",
            "Vellanki B.O",
            "Ambapuram B.O",
            "Jaccampudi B.O",
            "Tadepalli B.O",
            "H Mutyalampadu B.O",
            "Sunnampadu B.O",
            "Vellaturu B.O",
            "Velagaleru B.O",
            "Gosala B.O",
            "Ambedkarnagar B.O",
            "Gopuvanipalem B.O",
            "Gurazada B.O",
            "Kanumuru B.O",
            "Marrivada B.O",
            "Saipuram B.O",
            "Tadanki B.O",
            "Velpuru B.O",
            "Guruvindapalli B.O",
            "Iluru B.O",
            "Inapur B.O",
            "Kuderu B.O",
            "Madhurapuram B.O",
            "Patamatalankapalli B.O",
            "Srirangapuram B.O",
            "Chintalapadu B.O",
            "Eturu B.O",
            "Guttavaripalem B.O",
            "Thotaravulapadu B.O",
            "Turlapadu B.O",
            "Savaragudem B.O",
            "Chandrgudem B.O",
            "Chandrala B.O",
            "China Nandigama B.O",
            "Ganapavaram B.O",
            "Konduru B.O",
            "Kuntamukkala B.O",
            "Morusumilli B.O",
            "Naguluru B.O",
            "Pulluru B.O",
            "Anigandlapadu B.O",
            "Gopinenipalem B.O",
            "Gummadidurru B.O",
            "Kannevidu B.O",
            "Makkapeta B.O",
            "Muchintala B.O",
            "Mundlapadu B.O",
            "Singavaram B.O",
            "Sivapuram B.O",
            "Subbayyagudem B.O",
            "Vemavaram B.O",
            "Venkatapuram B.O",
            "Guntupalli B.O",
            "Paidurupadu B.O",
            "Rayanapadu B.O",
            "Bhadrirajupalem B.O",
            "Chagantipadu B.O",
            "Devarapalli B.O",
            "Pamulalanka B.O",
            "Valluripalem B.O",
            "Chilukuru B.O",
            "Jupudi B.O",
            "Kotikalapudi B.O",
            "Ketanakonda B.O",
            "Mulapadu B.O",
            "Dabbakupalli B.O",
            "Kakaravai B.O",
            "Khambampadu B.O",
            "Lingala B.O",
            "Machinenipalem B.O",
            "Polampalli B.O",
            "Pentalavarigudem B.O",
            "Talluru B.O",
            "Vemulanarva B.O",
            "Chowtapalli B.O",
            "Damulur B.O",
            "Mangollu B.O",
            "Chopparametla B.O",
            "Edara B.O",
            "Idulagudem B.O",
            "Krishnavaram B.O",
            "Kotha Edara B.O",
            "Narasingapalem B.O",
            "Nugondapalli B.O",
            "Seetharampuram B.O",
            "Sagguru B.O",
            "Sobhanapuram B.O",
            "Along S.O",
            "Arunachal Pradesh Secretariat S.O",
            "Anini S.O",
            "Banderdewa S.O",
            "Basar S.O (West Siang)",
            "Bhalukpong S.O",
            "Bordumsa S.O",
            "Bomdila S.O",
            "Changlang S.O",
            "Chowkham S.O",
            "Daporijo S.O",
            "Deomali S.O",
            "Dirang S.O",
            "Doimukh S.O",
            "Hayuliang S.O",
            "Hill Top S.O",
            "Tezu S.O",
            "Tuting S.O",
            "Vijoynagar S.O",
            "Yingkiong S.O",
            "Ziro S.O",
            "Roing S.O",
            "Jairampur S.O (Changlang)",
            "Jang S.O",
            "Khonsa S.O",
            "Kimin S.O",
            "Kalaktang S.O",
            "Likabali S.O",
            "Longding S.O",
            "Lumla S.O",
            "Mahadevpur S.O (Lohit)",
            "Mechuka S.O",
            "Mebo S.O",
            "Miao S.O",
            "Naharlagun S.O",
            "Nampong S.O",
            "Namsai S.O",
            "Nirjuli S.O",
            "Palin S.O",
            "Pasighat S.O",
            "Ranga Nadi Project S.O",
            "Ram Krishna Mission S.O",
            "Rupa S.O",
            "Seppa S.O",
            "Seijosa S.O",
            "Sunpura S.O",
            "Tawang S.O",
            "Tenga Market S.O",
            "Sagalee S.O",
            "Itanagar H.O",
            "Anelih B.O",
            "Etalin B.O",
            "Palizi B.O",
            "Thrizino B.O",
            "Lhou B.O",
            "Kanubari B.O B.O",
            "Siiro B.O",
            "Hari B.O",
            "Hong B.O",
            "Jully B.O",
            "Milonpur B.O",
            "Kolaptukar B.O",
            "Pessing B.O",
            "Rahung B.O",
            "Suchana Nagar B.O",
            "Munna Camp B.O",
            "Kaimai B.O",
            "Namphai B.O",
            "Kebang B.O",
            "Paglam B.O",
            "Geku B.O",
            "Korang B.O",
            "Koyu B.O",
            "Ledum B.O",
            "Nari B.O",
            "Oyan B.O",
            "Pangin B.O",
            "Ruksin B.O",
            "Rani B.O",
            "Renging B.O",
            "Riga B.O",
            "Sille B.O",
            "Yagrung B.O",
            "Mengio B.O",
            "Yazali B.O",
            "Chimpu B.O",
            "Donyi Polo B.O",
            "Vidya Vihar B.O",
            "Shergaon B.O",
            "Abango B.O",
            "Anupam B.O",
            "Bolung B.O",
            "Bijari B.O",
            "Bomjir B.O",
            "Desali B.O",
            "Dambuk B.O",
            "Elopa B.O",
            "Hunli B.O",
            "Iduli B.O",
            "Jia B.O",
            "Kronli B.O",
            "Koronu B.O",
            "Meka B.O",
            "Parbuk B.O",
            "Santipur B.O",
            "Bameng B.O",
            "Bana B.O",
            "Chyangtajo B.O",
            "Pipu-dipu B.O",
            "P.Kessang B.O",
            "Khenewa B.O",
            "Lada B.O",
            "Veo B.O",
            "Yealing B.O",
            "B.Supply B.O",
            "Kitpi B.O",
            "Lumberdung B.O",
            "Sakpret B.O",
            "Temple Gompa B.O",
            "Dedza B.O",
            "Dahung B.O",
            "Singchung B.O",
            "Changliang B.O",
            "Gohaingaon B.O",
            "Danglat B.O",
            "Lohitpur B.O",
            "Tindolong B.O",
            "Tafragam B.O",
            "Loiliang B.O",
            "Tezu Govt. College B.O",
            "Gelling B.O",
            "Migging B.O",
            "Singa B.O",
            "Gandhigram B.O",
            "Two Hut B.O",
            "Karko B.O",
            "Mariyang B.O",
            "Shimong B.O",
            "Boasimla B.O",
            "Deed B.O",
            "Godak B.O",
            "Hija B.O",
            "Joram B.O",
            "Old Ziro B.O",
            "Raga B.O",
            "Talo B.O",
            "Yachuli B.O",
            "Yangkang B.O",
            "Alubari B.O",
            "Chakma B.O",
            "Kamlang Nagar B.O",
            "Kherem B.O",
            "Medo B.O",
            "Momong B.O",
            "Wakro B.O",
            "Dumporijo B.O",
            "Giba B.O",
            "Maro B.O",
            "Muri B.O",
            "Nacho B.O",
            "Sippi B.O",
            "Siyum B.O",
            "Taksing B.O",
            "Taliha B.O",
            "Bagra B.O",
            "Bene B.O",
            "Darka B.O",
            "Kombo B.O",
            "Darak B.O",
            "Kambang B.O",
            "Kaying B.O",
            "Logum Jining B.O",
            "Monigong B.O",
            "Nikte B.O",
            "Payum B.O",
            "Rumgong B.O",
            "Tato B.O",
            "Vivek Nagar B.O",
            "Yomcha B.O",
            "Yoji Yora B.O",
            "Alinye B.O",
            "Balijan B.O",
            "Kokila B.O",
            "Sonajuli B.O",
            "Bame B.O",
            "Daring B.O",
            "Dali B.O",
            "Liromoba B.O",
            "Tirbin B.O",
            "Khellong B.O",
            "Tippi B.O",
            "Kherem Bisa B.O",
            "Lallung B.O",
            "Rajanagar B.O",
            "New Mohong B.O",
            "Vijoypur B.O",
            "Nafra B.O",
            "Salari B.O",
            "Bubang B.O",
            "Khemiyong B.O",
            "Namdang B.O",
            "Namtok B.O",
            "Rangfra Govt.College B.O",
            "Ranglum B.O",
            "Tabarijo B.O",
            "Lemiking B.O",
            "Lepajaring B.O",
            "Hukanjuri B.O",
            "Namsang B.O",
            "Namsang Mukh B.O",
            "Narottam Nagar B.O",
            "Soha B.O",
            "Dirang Basti B.O",
            "Lish B.O",
            "Sangti B.O",
            "Senge B.O",
            "Arunachal University B.O",
            "Kheel B.O",
            "Midpu B.O",
            "Chaglagam B.O",
            "Goiliang B.O",
            "Hawai B.O",
            "Kibitho B.O",
            "Khopa B.O",
            "Meteliang B.O",
            "Wallong B.O",
            "Yatong B.O",
            "Manmao B.O",
            "Thingbu B.O",
            "Mukto B.O",
            "Balemu B.O",
            "Tenzingaon B.O",
            "Borduria B.O",
            "Dadam B.O",
            "Kapu B.O",
            "Kanubari B.O",
            "Khonsa Basti B.O",
            "Khela B.O",
            "Kheti B.O",
            "Lazu B.O",
            "Thinsa B.O",
            "Tupi B.O",
            "Valley view B.O",
            "Hawa Camp B.O",
            "Garu B.O",
            "Gensi B.O",
            "Khotnu B.O",
            "K/nokno B.O",
            "Longfong B.O",
            "Niausa B.O",
            "Nginu B.O",
            "Minthong B.O",
            "Pangchou B.O",
            "Senewa B.O",
            "Tissa B.O",
            "Wakka B.O",
            "Gispu B.O",
            "Zemithang B.O",
            "Kumari Kachari B.O",
            "Padumani B.O",
            "Ayeng B.O",
            "Borguli B.O",
            "Namsing B.O",
            "Ngopok B.O",
            "Silluk B.O",
            "Sirem B.O",
            "Chopelling B.O",
            "Deban B.O",
            "Kharsang B.O",
            "Kutum Basti B.O",
            "Manabhum B.O",
            "Namchik B.O",
            "Dharampur B.O",
            "Model Village B.O",
            "Yupia B.O",
            "Diyun B.O",
            "Innao B.O",
            "Jaipur B.O",
            "Kumsai B.O",
            "Lathao B.O",
            "Manmao B.O",
            "Nampong B.O",
            "Nanam B.O",
            "Piyong B.O",
            "Udaipur B.O",
            "Wingko B.O",
            "Chambang B.O",
            "Damin B.O",
            "Hiya B.O",
            "Koloriang B.O",
            "Nyapin B.O",
            "Sarli B.O",
            "Sangram B.O",
            "Tali B.O",
            "Adipassi B.O",
            "Balek B.O",
            "Bilat B.O",
            "Boleng B.O",
            "Dalbing B.O",
            "Damro B.O",
            "Debing B.O",
            "GTC B.O",
            "Anilgarh S.O",
            "Anipur S.O",
            "Badarpurghat S.O",
            "Barjalenga S.O",
            "Dullabcherra S.O",
            "Jaffirband S.O",
            "Jamira Bazar S.O",
            "Dwarband S.O",
            "Kalibari Bazar S.O",
            "Kalinagar S.O",
            "Katlacherra S.O",
            "Lakshmisahar S.O",
            "Lala S.O",
            "Manipur Bagan S.O",
            "Monacherra S.O",
            "Olivacherra S.O",
            "Panchgram S.O",
            "Ramkrishnanagar S.O",
            "Ratabari S.O",
            "Ratanpur Road S.O",
            "Rajyeswarpur S.O",
            "Badarpur Bazar S.O",
            "Baraigram S.O",
            "Bazarghat S.O (Karimganj)",
            "Bazaricherra Bazar S.O",
            "Behara Bazar S.O",
            "Bhanga Bazaar S.O",
            "Chandkhira S.O",
            "Char Bazar S.O",
            "Hatikhira S.O",
            "Isabeel S.O",
            "Jalalpur S.O (Cachar)",
            "Kalain S.O",
            "Kaliganj Bazar S.O",
            "Karimganj Bazar S.O",
            "Karimganj Court S.O",
            "Karimganj Station Road S.O",
            "Katigorah S.O",
            "Katirail S.O",
            "Kayasthagram S.O",
            "Mahisashan S.O",
            "Nilam Bazar S.O",
            "Patharkandi S.O",
            "Settlement Road S.O",
            "Silchar Road S.O",
            "Subashnagar S.O",
            "Tillabazar S.O",
            "Arunachal S.O",
            "Assam University S.O",
            "Banskandi S.O",
            "Borkhola S.O",
            "Bekirpar S.O",
            "Bhaga Bazar S.O",
            "Binnakandi Ghat S.O",
            "Dalu S.O",
            "Derby S.O",
            "Dewan S.O",
            "Dewanji Bazar S.O",
            "Dholai Bazar S.O",
            "Fulertal S.O",
            "G C College S.O",
            "Haflong Ptc S.O",
            "Harengajao S.O",
            "Hospital Road S.O (Cachar)",
            "Jarailtala Bazar S.O",
            "Jirighat S.O",
            "Joypur Rajabazar S.O",
            "Kabuganj Bazar S.O",
            "Kumbhir S.O",
            "Kumbhirgram Airport S.O",
            "Lakhipur S.O (Cachar)",
            "Langting S.O",
            "Link Road S.O (Cachar)",
            "Madhurbond S.O",
            "Mahur S.O",
            "Maibong S.O",
            "Malugram S.O",
            "Matinagar S.O",
            "Meherpur S.O",
            "Narsingpur S.O",
            "Pailapool S.O",
            "Palonghat S.O",
            "Rongpur S.O",
            "Silchar Medical College S.O",
            "Silchar REC S.O",
            "Silcuri S.O",
            "Sonabarighat S.O",
            "Sonaimukh S.O",
            "Srikona S.O",
            "Salganga S.O",
            "Silchar Court S.O",
            "Tarapur S.O (Cachar)",
            "Tarapur Part VII S.O",
            "Udarbond S.O",
            "Umrangshu S.O",
            "Vivekananda Road S.O",
            "Badarpur S.O (Karimganj)",
            "Haflong S.O",
            "Rangirkhari S.O",
            "Chariali S.O",
            "Jhagrarpar S.O",
            "IBC Guwahati S.O",
            "Moran S.O",
            "Merapani S.O",
            "Monkhooli S.O.",
            "Sapekhati S.O",
            "Sepon S.O",
            "Simaluguri S.O",
            "Sonari S.O (Sibsagar)",
            "Suffry S.O",
            "Tamulichiga S.O",
            "Barpathar S.O",
            "Baruabamungaon S.O",
            "Bengenakhowa S.O",
            "Badulipaar S.O",
            "Bokakhat S.O",
            "Dergaon S.O",
            "Dergaon Chariali S.O",
            "Dhekial S.O",
            "Furkating S.O",
            "Kamarbandha Ali S.O",
            "Kamargaon S.O (Golaghat)",
            "Kaziranga National Park S.O",
            "Letekujaan S.O",
            "Maheema S.O",
            "Numaligarh S.O",
            "Numaligarh Refinery Project S.O",
            "Oating S.O",
            "Ptc Dergaon S.O",
            "Sarupathar S.O",
            "Rajmai S.O",
            "Lahdoigarh Chariali S.O",
            "Assam Agriculture University S.O",
            "Bahana S.O",
            "Barbheta S.O",
            "Bhogdaimukh S.O",
            "Borholla S.O",
            "Cinnamara S.O",
            "Chengeli Gaon S.O",
            "Dakhin Pat Satra S.O",
            "Dhalarsatra S.O",
            "Garali S.O",
            "Garmursatra S.O",
            "Gatanga S.O",
            "Jengraimukh S.O",
            "Jorhat Engg College S.O",
            "Jorhat Reserch Lab S.O",
            "Kakilamukh S.O",
            "Kakajan S.O",
            "Kamalabari S.O",
            "Khorikotia S.O",
            "Korokatoly S.O",
            "Macharhat S.O",
            "Majulibongaon S.O",
            "Mariani S.O",
            "Nakachari S.O",
            "Neamatighat S.O",
            "Na Ali Dhekiajuli S.O",
            "Ongc Jorhat S.O");


    public static List<String> getCities() {
        return cities;
    }

    public static void setCities(List<String> cities) {
        Cities.cities = cities;
    }
}
